services:
  citra-room:
    image: k4rian/citra-room:latest
    container_name: citra-room
    hostname: citra
    volumes:
      - data:/home/citra
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - citra-room.env
    secrets:
      - citraroom
    ports:
      - 24872:24872/tcp
      - 24872:24872/udp
    restart: unless-stopped

volumes:
  data:

secrets:
  citraroom:
    file: ./secret.txt